<a href="https://colab.research.google.com/github/Liliana2233/Tareas/blob/main/tarea_01_python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [37]:
nombre = "Liliana"
edad = 30

print(f"Hola, me llamo {nombre} y tengo {edad} años.")

Hola, me llamo Liliana y tengo 30 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [38]:
numeros = [10, 25, 3, 47, 8, 15]

# Imprimir el primer y el último elemento
print("Primer elemento:", numeros[0])
print("Último elemento:", numeros[-1])

# Imprimir los tres primeros elementos usando slicing
print("Tres primeros elementos:", numeros[:3])

# Agregar el número 99 al final de la lista
numeros.append(99)

# Imprimir la lista actualizada
print("Lista actualizada:", numeros)



Primer elemento: 10
Último elemento: 15
Tres primeros elementos: [10, 25, 3]
Lista actualizada: [10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [39]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante["promedio"] >= 6:
    print("Aprobado")
else:
    print("Reprobado")

Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [40]:
# Tu respuesta aquí
def calcular_area(base, altura):
    return base * altura / 2

resultado = calcular_area(base=5, altura=8)
print(resultado)


20.0


P5. Usa una list comprehension para crear una lista con los cuadrados de los números del 1 al 10.
Imprime la lista resultante.

In [41]:

# Crear lista con los cuadrados del 1 al 10
cuadrados = [numero ** 2 for numero in range(1, 11)]

# Imprimir el resultado
print("=== Cuadrados de los números del 1 al 10 ===")
print(cuadrados)

=== Cuadrados de los números del 1 al 10 ===
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [42]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [43]:

import numpy as np

# 1. Arreglo con valores decimales
arreglo = np.array([1.5, 2.5, 3.5, 4.5])
print("Arreglo:", arreglo)
print("Shape:", arreglo.shape)
print("Dtype:", arreglo.dtype)
print()

# 2. Matriz de ceros 3x4
matriz_ceros = np.zeros((3, 4))
print("Matriz de ceros:")
print(matriz_ceros)
print("Shape:", matriz_ceros.shape)
print("Dtype:", matriz_ceros.dtype)
print()

# 3. Arreglo con linspace
arreglo_linspace = np.linspace(0, 1, 6)
print("Arreglo linspace:", arreglo_linspace)
print("Shape:", arreglo_linspace.shape)
print("Dtype:", arreglo_linspace.dtype)


Arreglo: [1.5 2.5 3.5 4.5]
Shape: (4,)
Dtype: float64

Matriz de ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Dtype: float64

Arreglo linspace: [0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,)
Dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [44]:

import numpy as np

# Crear el arreglo y convertirlo en una matriz 3x4
a = np.arange(1, 13)
matriz = a.reshape(3, 4)

print("=== Matriz 3 x 4 ===")
print(matriz)

# Calcular valores
valor_maximo = matriz.max()
valor_minimo = matriz.min()
indice_maximo = tuple(int(x) for x in np.unravel_index(matriz.argmax(), matriz.shape))

print("\n=== Resultados ===")
print(f"Valor máximo: {valor_maximo}")
print(f"Valor mínimo: {valor_minimo}")
print(f"Posición del valor máximo (fila, columna): {indice_maximo}")



=== Matriz 3 x 4 ===
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

=== Resultados ===
Valor máximo: 12
Valor mínimo: 1
Posición del valor máximo (fila, columna): (2, 3)


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [45]:

# Tu respuesta aquí
import numpy as np

np.random.randint(1, 21, 5)

arreglo1=np.random.randint(1,20,5)
arreglo2=np.random.randint(1,20,5)
print("\nArreglo 1:\n", arreglo1)
print("\nArreglo 2:\n", arreglo2)

suma=arreglo1+arreglo2
print("\nSuma:\n", suma)

resta=arreglo1-arreglo2
print("\nResta:\n", resta)

multiplicacion=arreglo1*arreglo2
print("\nMultiplicación:\n", multiplicacion)




Arreglo 1:
 [17  4 18  8  4]

Arreglo 2:
 [ 2  6 10  4 18]

Suma:
 [19 10 28 12 22]

Resta:
 [ 15  -2   8   4 -14]

Multiplicación:
 [ 34  24 180  32  72]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [46]:

import numpy as np

# Arreglo de notas
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Indexación booleana: notas mayores o iguales a 6
notas_aprobadas = notas[notas >= 6]

print("=== Notas Aprobadas (>= 6) ===")
print(notas_aprobadas)



=== Notas Aprobadas (>= 6) ===
[ 8.5  6.   9.2  7.8 10. ]
